apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: jenkins-app
    helm:
      parameters:
      - name: ingress.inghost
        value: jenkins-app-argo.k8s-7.sa
    repoURL: https://goshaker.github.io/helm-27-24/
    targetRevision: 0.3.0
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
  - deployStartedAt: "2024-03-06T19:36:11Z"
    deployedAt: "2024-03-06T19:36:12Z"
    id: 0
    revision: 0.3.0
    source:
      chart: jenkins-app
      helm:
        parameters:
        - name: ingress.inghost
          value: jenkins-app-argo.k8s-7.sa
      repoURL: https://goshaker.github.io/helm-27-24/
      targetRevision: 0.3.0
  operationState:
    finishedAt: "2024-03-06T19:36:12Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        prune: true
        revision: 0.3.0
        syncOptions:
        - CreateNamespace=true
    phase: Succeeded
    startedAt: "2024-03-06T19:36:11Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Namespace
        message: namespace/jenkins-app created
        name: jenkins-app
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ServiceAccount
        message: serviceaccount/jenkins-app created
        name: jenkins-app
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Secret
        message: secret/jenkins-secret created
        name: jenkins-secret
        namespace: jenkins-app
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/my-basic-config created
        name: my-basic-config
        namespace: jenkins-app
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/my-jenkins-config created
        name: my-jenkins-config
        namespace: jenkins-app
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRoleBinding
        message: "clusterrolebinding.rbac.authorization.k8s.io/jenkins-app-binding
          reconciled. reconciliation required create\n\tmissing subjects added:\n\t\t{Kind:ServiceAccount
          APIGroup: Name:default Namespace:jenkins-app}. clusterrolebinding.rbac.authorization.k8s.io/jenkins-app-binding
          configured. Warning: resource clusterrolebindings/jenkins-app-binding is
          missing the kubectl.kubernetes.io/last-applied-configuration annotation
          which is required by  apply.  apply should only be used on resources created
          declaratively by either  create --save-config or  apply. The missing annotation
          will be patched automatically."
        name: jenkins-app-binding
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/jenkins-app created
        name: jenkins-app
        namespace: jenkins-app
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/jenkins-app created
        name: jenkins-app
        namespace: jenkins-app
        status: Synced
        syncPhase: Sync
        version: v1
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/helm-jenkins-ingress created
        name: helm-jenkins-ingress
        namespace: jenkins-app
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 0.3.0
      source:
        chart: jenkins-app
        helm:
          parameters:
          - name: ingress.inghost
            value: jenkins-app-argo.k8s-7.sa
        repoURL: https://goshaker.github.io/helm-27-24/
        targetRevision: 0.3.0
  reconciledAt: "2024-03-06T19:48:43Z"
  resources:
  - kind: ConfigMap
    name: my-basic-config
    namespace: jenkins-app
    status: Synced
    version: v1
  - kind: ConfigMap
    name: my-jenkins-config
    namespace: jenkins-app
    status: Synced
    version: v1
  - kind: Namespace
    name: jenkins-app
    status: Synced
    version: v1
  - kind: Secret
    name: jenkins-secret
    namespace: jenkins-app
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: jenkins-app
    namespace: jenkins-app
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: jenkins-app
    namespace: default
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: jenkins-app
    namespace: jenkins-app
    status: Synced
    version: v1
  - group: networking.k8s.io
    health:
      status: Healthy
    kind: Ingress
    name: helm-jenkins-ingress
    namespace: jenkins-app
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: jenkins-app-binding
    status: Synced
    version: v1
  sourceType: Helm
  summary:
    externalURLs:
    - http://jenkins-app-argo.k8s-7.sa/
    images:
    - jfrog.it-academy.by/public/jenkins-ci:gakobiakov
  sync:
    comparedTo:
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      source:
        chart: jenkins-app
        helm:
          parameters:
          - name: ingress.inghost
            value: jenkins-app-argo.k8s-7.sa
        repoURL: https://goshaker.github.io/helm-27-24/
        targetRevision: 0.3.0
    revision: 0.3.0
    status: Synced
